apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx_prod1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ephur/orb-app-test.git
    targetRevision: HEAD
    path: helm/prod1
  destination:
    server: https://kubernetes.default.svc
    namespace: prod1

spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod1
