apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ephur/orb-app-test.git
    targetRevision: HEAD
    path: helm/dev1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev1
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev1
